# Generated by Django 5.0.6 on 2024-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptmodel',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='transcriptmodel',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='transcriptmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transcriptmodel',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
