# Generated by Django 5.0.6 on 2024-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transcriptmodel_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptmodel',
            name='title',
            field=models.CharField(default='My Audio Transcript', max_length=100),
        ),
    ]
