# Generated by Django 5.0.6 on 2024-07-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transcriptmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptmodel',
            old_name='media_file',
            new_name='file',
        ),
    ]
