# Generated by Django 5.0.6 on 2024-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_transcriptmodel_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=255),
        ),
    ]
