# Generated by Django 5.0.6 on 2024-07-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sentence_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='api.transcriptmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='utterance',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='api.speaker'),
        ),
    ]
