# Generated by Django 5.0.6 on 2024-07-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sentence_sentiment_sentence_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='stop_time',
            new_name='end_time',
        ),
    ]
