# Generated by Django 5.0.6 on 2024-07-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_stop_time_sentence_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=16)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='api.transcriptmodel')),
            ],
        ),
    ]
