# Generated by Django 5.0.6 on 2024-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='pause',
            name='before_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(),
        ),
    ]
